// <auto-generated />
using DesignYourOwnAdventure.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesignYourOwnAdventure.Infrastructure.Migrations
{
    [DbContext(typeof(AdventureContext))]
    partial class AdventureContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("DesignYourOwnAdventure.Core.Entities.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BinaryTreeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnswerId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            BinaryTreeId = 1,
                            Steps = "[\"L\",\"L\",\"R\",\"L\"]",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DesignYourOwnAdventure.Core.Entities.BinaryTree<DesignYourOwnAdventure.Core.Entities.Question>", b =>
                {
                    b.Property<int>("BinaryTreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Root")
                        .HasColumnType("TEXT");

                    b.HasKey("BinaryTreeId");

                    b.ToTable("Adventures");

                    b.HasData(
                        new
                        {
                            BinaryTreeId = 1,
                            Root = "{\"Left\":{\"Left\":{\"Left\":{\"Data\":{\"Text\":\"Get it\"}},\"Right\":{\"Data\":{\"Text\":\"Do jumping jacks first!\"}},\"Data\":{\"Text\":\"Are you sure?\"}},\"Right\":{\"Left\":{\"Data\":{\"Text\":\"What are you waiting for? Grab it now.\"}},\"Right\":{\"Data\":{\"Text\":\"Wait till you find a sinful, unforgettable doughnut.\"}},\"Data\":{\"Text\":\"Is it a good donut?\"}},\"Data\":{\"Text\":\"Do I deserve it?\"}},\"Right\":{\"Data\":{\"Text\":\"Maybe you want an apple?\"}},\"Data\":{\"Text\":\"Do I want a Donut?\"}}"
                        });
                });

            modelBuilder.Entity("DesignYourOwnAdventure.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DisplayName = "Dishan",
                            Email = "dishanrajapaksha@outlook.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
